# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: DeveloperTools
  licenses: Apache-2.0
  images: |
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.30.3-debian-12-r4
    - name: mariadb
      image: docker.io/bitnami/mariadb:10.11.8-debian-12-r6
    - name: prometheus-rsocket-proxy
      image: docker.io/bitnami/prometheus-rsocket-proxy:1.5.3-debian-12-r26
    - name: spring-cloud-dataflow
      image: docker.io/bitnami/spring-cloud-dataflow:2.11.4-debian-12-r2
    - name: spring-cloud-dataflow-composed-task-runner
      image: docker.io/bitnami/spring-cloud-dataflow-composed-task-runner:2.11.4-debian-12-r2
    - name: spring-cloud-skipper
      image: docker.io/bitnami/spring-cloud-skipper:2.11.4-debian-12-r2
apiVersion: v2
appVersion: 2.11.4
dependencies:
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.x.x
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - dataflow-database
  version: 19.x.x
- condition: kafka.enabled
  name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 30.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Spring Cloud Data Flow is a microservices-based toolkit for building streaming and batch data processing pipelines in Cloud Foundry and Kubernetes.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/spring-cloud-dataflow/img/spring-cloud-dataflow-stack-220x234.png
keywords:
- spring-cloud
- dataflow
- skipper
- spring
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: spring-cloud-dataflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/spring-cloud-dataflow
version: 31.0.0
