# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: CMS
  licenses: Apache-2.0
  images: |
    - name: gotrue
      image: docker.io/bitnami/gotrue:2.155.6-debian-12-r3
    - name: jwt-cli
      image: docker.io/bitnami/jwt-cli:6.1.0-debian-12-r5
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.30.3-debian-12-r4
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r27
    - name: postgrest
      image: docker.io/bitnami/postgrest:11.2.2-debian-12-r31
    - name: supabase-postgres
      image: docker.io/bitnami/supabase-postgres:15.6.1-debian-12-r2
    - name: supabase-postgres-meta
      image: docker.io/bitnami/supabase-postgres-meta:0.83.2-debian-12-r3
    - name: supabase-realtime
      image: docker.io/bitnami/supabase-realtime:2.30.14-debian-12-r2
    - name: supabase-storage
      image: docker.io/bitnami/supabase-storage:1.8.2-debian-12-r2
    - name: supabase-studio
      image: docker.io/bitnami/supabase-studio:1.24.5-debian-12-r4
apiVersion: v2
appVersion: 1.24.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
- condition: kong.enabled
  name: kong
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Supabase is an open source Firebase alternative. Provides all the necessary backend features to build your application in a scalable way. Uses PostgreSQL as datastore.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/supabase/img/supabase-stack-220x234.png
keywords:
- development
- dashboards
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: supabase
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/supabase
version: 5.3.3
